### ISSUE TITLE
Resign

### ISSUE THREAD

**Issue by HemanthJabalpuri** [netmackan/CertTools#5]
It needs to be resigned since it fails to install

**Comment by netmackan** [comment]
What Android version do you have?
Where did you get the app from, i.e. Play Store or F-Droid?

**Comment by netmackan** [comment]
Possibly same as #2

**Comment by HemanthJabalpuri** [comment]
> What Android version do you have?
> Where did you get the app from, i.e. Play Store or F-Droid?

4.4.2 unable to install from F-Droid build...
if i resign a install then it works...
